### PR TITLE
[ch5230] See how we can sort invoices by metadata information

### PR DESCRIPTION
**Pull request by dmitriyhumminghomes**
#### Summary

Added migration to alert Invoice's metadata field (to use JSONField from postgres)

#### Clubhouse Task(s)

[ch5230]  https://app.clubhouse.io/humming-homes/story/5230/spike-see-how-we-can-sort-invoices-by-metadata-information

#### How to Test

Nothing specific

### CODE REVIEW

**Review by jgrana — APPROVED** [review]
hope this works, will this automatically cast all text to json?

**Comment by dmitriyhumminghomes** [comment]
@jgrana hey John, there was a case when migrations were applied without problems, but DB wasn't up to date. I figured out how to test it and verified that solution from yesterday didn't work. I found a different workaround.

- I tested migration with metadata field alert locally and it doesn't work, it doesn't cast Invoice's metadata from text to json, but I found a way to get this done by recreating metadata field. I tested it and it worked, filtering by Invoice's metadata worked (screenshot).
- One thing that after recreating, Invoice's metadata data is lost but it can be repopulated by running "python manage.py djstripe_sync_models"

image (2)

**Review by prav-tadikonda — APPROVED** [review]
Looks good!

**Comment by prav-tadikonda** [comment]
@dmitriyhumminghomes can you instead just create a new field called `new_metadata` with JSON field? And then run the script to populate that field, and then delete old `metatdata` field, and rename `new_metadata` => `metadata`

**Review by prav-tadikonda — APPROVED** [review]

**Pull request merged**
